[package]
name = "tokio-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4.4"
tempfile = "3"
anyhow = "1"
base64 = "0.22.1"
serde = "1.0.219"
reqwest = "0.12.22"
bytes = "1.10.1"
