[package]
name = "tokio-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3"
rayon = "1.10.0"
anyhow = "1"
base64 = "0.22.1"
serde = "1.0.219"
